# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

LABEL io.k8s.description="A child container using ONBUILD COPY" \
      io.k8s.display-name="A child container" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="apache"

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chown -R g=u /var/run/httpd /var/log/httpd

USER 1001
